config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'services', to: 'pages#services'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = 'Votre article a été crée avec succès !'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "L'article a été modifié"
      redirect_to article_path(@article)
    else
      flash[:notice] = "L'article n'a pas pu été modifié"
      render 'edit'
    end
  end

  def index
    @article = Article.all
  end

  def destroy
    @article.destroy
    flash[:notice] = "L'article a été supprimé"
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, :reading_time, :category)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def services
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>Les erreurs suivantes ont empêché l'article la sauvegarde de l'article :</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :reading_time %><br>
    <%= f.text_field :reading_time %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Modifier un article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>

<p>
  <%= link_to "Create new article", new_article_path %>
</p>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Catégorie</th>
    <th>Temps de lecture</th>
  </tr>
  <% @article.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td><%= article.category %></td>
      <td><%= article.reading_time %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Etes-vous sûr ?"} %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to 'Back', articles_path %>
</p>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1>Voici l'article selectionné :</h1>

<p>
 Titre: <%= @article.title %>
</p>

<p>
 Description: <%= @article.description %>
</p>

<p>
 Catégorie: <%= @article.category %>
</p>

<p>
 Temps de lecture: <%= @article.reading_time %>
</p>

<p>
  <%= link_to "Edit", edit_article_path(@article) %>
</p>

<p>
  <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>
</p>

<p>
  <%= link_to 'Back', articles_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>just-o-naturel : naturopathe à Epernon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <!-- navbar sur toutes les pages -->
    <% render 'shared/navbar' %>

    <!-- messages d'erreurs liés à devise -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <!-- messages d'erreurs liés aux articles -->
    <% flash.each do |name, msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
    <% end %>

  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to Blog</h1>

  <%= link_to 'services', services_path %>
  <%= link_to 'Home', root_path %>

app/views/pages/services.html.erb
<h1>About Blog</h1>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>